### ISSUE TITLE
KeyError: 'option_combo'

### ISSUE THREAD

**Issue by Clairewangxiaotong** [vn-crypto/vnpy_deribit#6]
连接出了问题

 main_engine.add_gateway(gateway_class=DeribitGateway)
 main_engine.add_gateway(gateway_class=BinanceSpotGateway)

[2022-11-04T18:22:56.945621]: Unhandled WebSocket Error:<class 'KeyError'>
LastSentText:
{"jsonrpc": "2.0", "id": 308, "method": "private/get_account_summary", "params": {"currency": "ETH"}}
LastReceivedText:
{"jsonrpc":"2.0","id":296,"result":[{"tick_size":0.0005,"taker_commission":0.0003,"strike":16000.0,"settlement_period":"day","settlement_currency":"BTC","rfq":false,"quote_currency":"BTC","price_index":"btc_usd","option_type":"call","min_trade_amount":0.1,"maker_commission":0.0003,"kind":"option","is_active":true,"instrument_name":"BTC-5NOV22-16000-C","instrument_id":237400,"expiration_timestamp":1667635200000,"creation_timestamp":1667462460000,"counter_currency":"USD","contract_size":1.0,"block_trade_commission":0.0003,"base_currency":"BTC"},{"tick_size":0.0005,"taker_commission":0.0003,"strike":16000.0,"settlement_period":"day","settlement_currency":"BTC","rfq":false,"quote_currency":"BTC","price_index":"btc_usd","option_type":"put","min_trade_amount":0.1,"maker_commission":0.0003,"kind":"option","is_active":true,"instrument_name":"BTC-5NOV22-16000-P","instrument_id":237401,"expiration_timestamp":1667635200000,"creation_timestamp":1667462460000,"counter_currency":"USD","contract_size
Exception trace: 
Traceback (most recent call last):
  File "D:\Anaconda\envs\vnpy\lib\site-packages\vnpy_websocket\websocket_client.py", line 187, in _run
    self.on_packet(data)
  File "D:\Anaconda\envs\vnpy\lib\site-packages\vnpy_deribit\deribit_gateway.py", line 384, in on_packet
    callback(packet)
  File "D:\Anaconda\envs\vnpy\lib\site-packages\vnpy_deribit\deribit_gateway.py", line 438, in on_query_instrument
    product=PRODUCT_DERIBIT2VT[d["kind"]],
KeyError: 'option_combo'

Process finished with exit code -1

**Comment by vn-crypto** [comment]
PR #5 merged
